name: BuildCV

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_cv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Compile CV
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: main.tex

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: CV-${{ steps.date.outputs.date }}
          release_name: CV-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./main.pdf
          asset_name: CV-LucasTimm.pdf
          asset_content_type: application/zip
